name: build
on:
  workflow_dispatch: # Thêm dòng này để kích hoạt nút "Run workflow" bằng tay

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    if: ${{ !startsWith(github.ref_name, 'mac') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - postgres: 18
            os: windows-2022
    steps:
      - uses: actions/checkout@v7

      - name: Install PostgreSQL 18 via Chocolatey
        run: |
          echo "=== Dang cai dat Postgres bang Chocolatey ==="
          choco install postgresql18 --no-progress -y
          
          echo "=== Cau hinh bien moi truong he thong ==="
          echo "PGROOT=C:\Program Files\PostgreSQL\18" >> %GITHUB_ENV%
          echo "C:\Program Files\PostgreSQL\18\bin" >> %GITHUB_PATH%
        shell: cmd
        
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      # 2. Bây giờ bạn có thể gọi thẳng nmake mà không cần dùng lệnh 'call "C:\..." && ^' nữa
      - name: Build and Test
        run: |
          nmake /NOLOGO /F Makefile.win
          nmake /NOLOGO /F Makefile.win install
        shell: cmd

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-pg${{ matrix.postgres }}-${{ matrix.os }}
          path: |
            **/*.dll
            **/*.so
            **/*.sql
            **/*.control
          if-no-files-found: warn

      - if: ${{ failure() }}
        name: Show test diffs on failure
        run: if exist regression.diffs cat regression.diffs
        shell: cmd
